CREATE TABLE "people" (
    "ID" INTEGER NOT NULL,
    "playerID" VARCHAR(9) NOT NULL,
    "birthYear" INTEGER NULL,
    "birthMonth" INTEGER NULL,
    "birthDay" INTEGER NULL,
    "birthCountry" VARCHAR(255) NULL,
    "birthState" VARCHAR(255) NULL,
    "birthCity" VARCHAR(255) NULL,
    "deathYear" INTEGER NULL,
    "deathMonth" INTEGER NULL,
    "deathDay" INTEGER NULL,
    "deathCountry" VARCHAR(255) NULL,
    "deathState" VARCHAR(255) NULL,
    "deathCity" VARCHAR(255) NULL,
    "nameFirst" VARCHAR(255) NULL,
    "nameLast" VARCHAR(255) NULL,
    "nameGiven" VARCHAR(255) NULL,
    "weight" INTEGER NULL,
    "height" INTEGER NULL,
    "bats" VARCHAR(255) NULL,
    "throws" VARCHAR(255) NULL,
    "debut" VARCHAR(255) NULL,
    "finalGame" VARCHAR(255) NULL,
    "retroID" VARCHAR(255) NULL,
    "bbrefID" VARCHAR(255) NULL,
    PRIMARY KEY ("ID")
);