CREATE TABLE "teamshalf" (
    "ID" INTEGER NOT NULL,
    "yearID" SMALLINT NOT NULL,
    "lgID" CHARACTER(2) NOT NULL,
    "teamID" CHARACTER(3) NOT NULL,
    "team_ID" INTEGER NULL,
    "Half" VARCHAR(1) NOT NULL,
    "divID" CHARACTER(1) NULL,
    "div_ID" INTEGER NULL,
    "DivWin" VARCHAR(1) NULL,
    "teamRank" SMALLINT NULL,
    "G" SMALLINT NULL,
    "W" SMALLINT NULL,
    "L" SMALLINT NULL,
    PRIMARY KEY ("ID"),
    FOREIGN KEY("team_ID") REFERENCES "teams" ("ID") ON UPDATE NO ACTION ON DELETE NO ACTION
);